/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import java.awt.Toolkit;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282227
 */
public class HomeFrame extends javax.swing.JFrame {
    
        private PacientesPanel pacientesPanel;
        private EspecialidadesPanel especialidadesPanel;
        private PlanoDeSaudePanel planoDeSaudePanel;
        private final int POS_X = 30;
        private final int POS_Y = 180;
        private final int POS_W = 750;
        private final int POS_H = 300;
        
       
    
    
    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/senai/sp/jandira/imagens/equipe-medica1.png")));
        initPanels( );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIcon = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        buttonAgenda = new javax.swing.JButton();
        buttonPacientes = new javax.swing.JButton();
        buttonEspecialidades = new javax.swing.JButton();
        buttonMedicos = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelIcon1 = new javax.swing.JLabel();
        buttonPlanoDeSaude = new javax.swing.JButton();
        buttonHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamento");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 105, 180));
        jPanel1.setLayout(null);

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Calendario.png"))); // NOI18N
        jPanel1.add(labelIcon);
        labelIcon.setBounds(30, 0, 70, 70);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelTitulo.setText("Agenda de Consultas");
        labelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelTitulo);
        labelTitulo.setBounds(280, 20, 240, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 70);

        buttonSair.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buttonSair.setForeground(new java.awt.Color(255, 255, 255));
        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Log-Outsair.png"))); // NOI18N
        buttonSair.setToolTipText("Sair do sistema");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSair);
        buttonSair.setBounds(750, 90, 30, 40);

        buttonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Agenda.png"))); // NOI18N
        buttonAgenda.setToolTipText("Agenda");
        buttonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgenda);
        buttonAgenda.setBounds(120, 100, 60, 40);

        buttonPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Paciente.png"))); // NOI18N
        buttonPacientes.setToolTipText("Cadastro De Pacientes");
        buttonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPacientes);
        buttonPacientes.setBounds(190, 100, 60, 39);

        buttonEspecialidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/estetoscopio.png"))); // NOI18N
        buttonEspecialidades.setToolTipText("Cadastro de especialidades Médicas");
        buttonEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEspecialidades);
        buttonEspecialidades.setBounds(330, 100, 60, 40);

        buttonMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/equipe-medica.png"))); // NOI18N
        buttonMedicos.setToolTipText("Cadastro de Médicos");
        buttonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMedicos);
        buttonMedicos.setBounds(260, 100, 60, 40);

        panelHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelHome.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 105, 180));
        jLabel1.setText("SISACON");
        panelHome.add(jLabel1);
        jLabel1.setBounds(10, 10, 250, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Sistema para Agendamento de Consultas");
        panelHome.add(jLabel2);
        jLabel2.setBounds(20, 60, 280, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Suporte Técnico:");
        panelHome.add(jLabel3);
        jLabel3.setBounds(590, 100, 200, 30);

        jLabel5.setText("Email: sisa@gmail.com");
        panelHome.add(jLabel5);
        jLabel5.setBounds(590, 140, 200, 16);

        jLabel6.setText("Telefone: 4602-8922");
        panelHome.add(jLabel6);
        jLabel6.setBounds(590, 160, 200, 16);

        jLabel7.setText("Site: www.sisa.com.br");
        panelHome.add(jLabel7);
        jLabel7.setBounds(590, 180, 190, 16);

        jPanel2.setBackground(new java.awt.Color(255, 105, 180));
        jPanel2.setForeground(new java.awt.Color(158, 168, 250));
        panelHome.add(jPanel2);
        jPanel2.setBounds(0, 90, 750, 2);

        labelIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Calendario.png"))); // NOI18N
        panelHome.add(labelIcon1);
        labelIcon1.setBounds(220, 10, 80, 60);

        getContentPane().add(panelHome);
        panelHome.setBounds(30, 180, 750, 300);

        buttonPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/plano-de-saude.png"))); // NOI18N
        buttonPlanoDeSaude.setToolTipText("Plano de saúde");
        buttonPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanoDeSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPlanoDeSaude);
        buttonPlanoDeSaude.setBounds(400, 100, 60, 39);

        buttonHome.setBackground(new java.awt.Color(255, 105, 180));
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/casa-limpa (1).png"))); // NOI18N
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHome);
        buttonHome.setBounds(40, 100, 70, 40);

        setSize(new java.awt.Dimension(816, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgendaActionPerformed
       panelHome.setVisible(false);
        especialidadesPanel.setVisible(false);
        buttonEspecialidades.setBackground(new java.awt.Color(255, 255, 255));
        buttonHome.setBackground(new java.awt.Color(255, 255, 255));
        buttonMedicos.setBackground(new java.awt.Color(255, 255, 255));
        buttonPacientes.setBackground(new java.awt.Color(255, 255, 255));
        buttonPlanoDeSaude.setBackground(new java.awt.Color(255, 255, 255));
        buttonAgenda.setBackground(new java.awt.Color(255, 105, 180));
        pacientesPanel.setVisible(false);
        planoDeSaudePanel.setVisible(false);
    }//GEN-LAST:event_buttonAgendaActionPerformed

    private void buttonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPacientesActionPerformed
        panelHome.setVisible(false);
        especialidadesPanel.setVisible(false);
        buttonEspecialidades.setBackground(new java.awt.Color(255, 255, 255));
        buttonHome.setBackground(new java.awt.Color(255, 255, 255));
        buttonMedicos.setBackground(new java.awt.Color(255, 255, 255));
        buttonPacientes.setBackground(new java.awt.Color(255, 105, 180));
        buttonPlanoDeSaude.setBackground(new java.awt.Color(255, 255, 255));
        buttonAgenda.setBackground(new java.awt.Color(255, 255, 255));
        pacientesPanel.setVisible(true);
        planoDeSaudePanel.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_buttonPacientesActionPerformed

    private void buttonEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspecialidadesActionPerformed
        buttonEspecialidades.setBackground(new java.awt.Color(255, 105, 180));
        buttonHome.setBackground(new java.awt.Color(255, 255, 255));
        buttonMedicos.setBackground(new java.awt.Color(255, 255, 255));
        buttonPacientes.setBackground(new java.awt.Color(255, 255, 255));
        buttonPlanoDeSaude.setBackground(new java.awt.Color(255, 255, 255));
        buttonAgenda.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setVisible(false);
        especialidadesPanel.setVisible(true);
        planoDeSaudePanel.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_buttonEspecialidadesActionPerformed

    private void buttonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicosActionPerformed
        panelHome.setVisible(false);
        especialidadesPanel.setVisible(false);
        buttonEspecialidades.setBackground(new java.awt.Color(255, 255, 255));
        buttonHome.setBackground(new java.awt.Color(255, 255, 255));
        buttonMedicos.setBackground(new java.awt.Color(255, 105, 180));
        buttonPacientes.setBackground(new java.awt.Color(255, 255, 255));
        buttonPlanoDeSaude.setBackground(new java.awt.Color(255, 255, 255));
        buttonAgenda.setBackground(new java.awt.Color(255, 255, 255));
        pacientesPanel.setVisible(false);
        planoDeSaudePanel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMedicosActionPerformed

    private void buttonPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanoDeSaudeActionPerformed
        panelHome.setVisible(false);
        especialidadesPanel.setVisible(false);
        buttonEspecialidades.setBackground(new java.awt.Color(255, 255, 255));
        buttonHome.setBackground(new java.awt.Color(255, 255, 255));
        buttonMedicos.setBackground(new java.awt.Color(255, 255, 255));
        buttonPacientes.setBackground(new java.awt.Color(255, 255, 255));
        buttonPlanoDeSaude.setBackground(new java.awt.Color(255, 105, 180));
        buttonAgenda.setBackground(new java.awt.Color(255, 255, 255));
        pacientesPanel.setVisible(false);
        planoDeSaudePanel.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanoDeSaudeActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        buttonEspecialidades.setBackground(new java.awt.Color(255, 255, 255));
        buttonHome.setBackground(new java.awt.Color(255, 105, 180));
        buttonMedicos.setBackground(new java.awt.Color(255, 255, 255));
        buttonPacientes.setBackground(new java.awt.Color(255, 255, 255));
        buttonPlanoDeSaude.setBackground(new java.awt.Color(255, 255, 255));
        buttonAgenda.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setVisible(true);
        especialidadesPanel.setVisible(false);
        pacientesPanel.setVisible(false);
        planoDeSaudePanel.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_buttonHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgenda;
    private javax.swing.JButton buttonEspecialidades;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonMedicos;
    private javax.swing.JButton buttonPacientes;
    private javax.swing.JButton buttonPlanoDeSaude;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelIcon1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables

    private void initPanels() {
        especialidadesPanel = new EspecialidadesPanel();
        especialidadesPanel.setBounds(POS_X, POS_Y, POS_W, POS_H);
        getContentPane().add(especialidadesPanel);
        especialidadesPanel.setVisible(false);
        
        pacientesPanel = new PacientesPanel();
        pacientesPanel.setBounds(POS_X, POS_Y, POS_W, POS_H);
        getContentPane().add(pacientesPanel);
        pacientesPanel.setVisible(false);
        
        planoDeSaudePanel = new PlanoDeSaudePanel();
        planoDeSaudePanel.setBounds(POS_X, POS_Y, POS_W, POS_H);
        getContentPane().add(planoDeSaudePanel);
        planoDeSaudePanel.setVisible(false);
    }

}
