/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import br.senai.sp.jandira.model.OperacaoEnum;
import br.senai.sp.jandira.model.PlanoDeSaude;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 22282176
 */
public class PlanoDeSaudeDialog extends javax.swing.JDialog {

    private PlanoDeSaude planoDeSaude;
    private OperacaoEnum operacao;

    /**
     * Creates new form PlanoDeSaudeDialog
     */
    public PlanoDeSaudeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.operacao = operacao;
        preencherTitulo();

    }

    public PlanoDeSaudeDialog(java.awt.Frame parent, boolean modal, OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        this.operacao = operacao;
        preencherTitulo();

    }

    PlanoDeSaudeDialog(
        java.awt.Frame parent,
        boolean modal,
        PlanoDeSaude p,
        OperacaoEnum operacaoEnum) {
        super(parent, modal);
        initComponents();
        planoDeSaude = p;
        this.operacao = operacao;
        preencherTitulo();
        preencherFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBaixo = new java.awt.Panel();
        jPanelContent = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNomePlano = new javax.swing.JTextField();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldCategoria = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        labelCategoria = new javax.swing.JLabel();
        jLabelValidade = new javax.swing.JLabel();
        jTextFieldValidade = new javax.swing.JTextField();
        jPanelHeader = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        IconeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        getContentPane().setLayout(null);

        panelBaixo.setBackground(new java.awt.Color(204, 204, 255));
        panelBaixo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBaixo.setPreferredSize(new java.awt.Dimension(690, 410));
        panelBaixo.setLayout(null);

        jPanelContent.setBackground(new java.awt.Color(204, 204, 255));
        jPanelContent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes de Plano de Saúde", 0, 0, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanelContent.setForeground(new java.awt.Color(255, 255, 255));
        jPanelContent.setLayout(null);

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCodigo.setText("Código");
        jPanelContent.add(jLabelCodigo);
        jLabelCodigo.setBounds(10, 40, 290, 50);

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(255, 204, 204));
        jTextFieldCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanelContent.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(10, 90, 140, 50);

        jTextFieldNomePlano.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanelContent.add(jTextFieldNomePlano);
        jTextFieldNomePlano.setBounds(10, 210, 360, 40);

        jLabelCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCategoria.setText("Categoria");
        jPanelContent.add(jLabelCategoria);
        jLabelCategoria.setBounds(10, 270, 280, 30);

        jTextFieldCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanelContent.add(jTextFieldCategoria);
        jTextFieldCategoria.setBounds(10, 320, 360, 40);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/cancelar.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelContent.add(jButtonCancelar);
        jButtonCancelar.setBounds(485, 320, 50, 40);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/diskette.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanelContent.add(jButtonSalvar);
        jButtonSalvar.setBounds(560, 320, 50, 40);

        labelCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCategoria.setText("Nome do Plano");
        jPanelContent.add(labelCategoria);
        labelCategoria.setBounds(20, 160, 290, 30);

        jLabelValidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelValidade.setText("Validade");
        jPanelContent.add(jLabelValidade);
        jLabelValidade.setBounds(440, 60, 120, 30);
        jPanelContent.add(jTextFieldValidade);
        jTextFieldValidade.setBounds(330, 100, 260, 30);

        panelBaixo.add(jPanelContent);
        jPanelContent.setBounds(30, 10, 620, 370);

        getContentPane().add(panelBaixo);
        panelBaixo.setBounds(0, 40, 690, 410);

        jPanelHeader.setBackground(new java.awt.Color(153, 0, 153));
        jPanelHeader.setLayout(null);

        TituloLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        TituloLabel.setText("PLANO DE SAÚDE - ADICIONAR");
        jPanelHeader.add(TituloLabel);
        TituloLabel.setBounds(80, 10, 320, 30);

        IconeLabel.setBackground(new java.awt.Color(255, 255, 255));
        IconeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Button-Adicionar.png"))); // NOI18N
        jPanelHeader.add(IconeLabel);
        IconeLabel.setBounds(20, 0, 60, 50);

        getContentPane().add(jPanelHeader);
        jPanelHeader.setBounds(0, 0, 690, 50);

        setSize(new java.awt.Dimension(706, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void preencherFormulario() {
        // NOI18N
        jTextFieldCodigo.setText(planoDeSaude.getCodigo().toString());
        jTextFieldNomePlano.setText(planoDeSaude.getOperadora());
        jTextFieldCategoria.setText(planoDeSaude.getCategoria());
        jTextFieldValidade.setText(planoDeSaude.getValidade().toString());
    }

    private void preencherTitulo() {
        TituloLabel.setText("PLANO DE SAÚDE - " + operacao);
        if (operacao == OperacaoEnum.EDITAR) {
            IconeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/edit32.png")));
        } else {
            IconeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/plano-de-saude.png")));
        }

    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (operacao == OperacaoEnum.ADICIONAR) {
            adicionar();
        } else {
            editar();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed
    
    
    

    
    private void adicionar() {
        if (jTextFieldNomePlano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome da Operadora ");
            jTextFieldNomePlano.requestFocus();
        }else if (jTextFieldCategoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite a descrição da Categoria ");
            jTextFieldCategoria.requestFocus();
        }else {
           
            PlanoDeSaude planoSaude = new PlanoDeSaude();
            planoSaude.setOperadora(jTextFieldNomePlano.getText());
            planoSaude.setCategoria(jTextFieldCategoria.getText());
            //planoSaude.setValidade(LocalDate.parse(jTextFieldValidade.getText(),formato));
            String[] dataArray = jTextFieldValidade.getText().split("/");
            
            int dia = Integer.parseInt(dataArray[0]);
            int mes = Integer.parseInt(dataArray[1]);
            int ano = Integer.parseInt(dataArray[2]);
            
            
            planoSaude.setValidade(LocalDate.of(ano, mes, dia));
            
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            
            
            PlanoDeSaudeDAO.gravar(planoSaude);

            JOptionPane.showMessageDialog(
                    this,
                    "Plano de saúde gravado com sucesso!",
                    "Plano de saúde",
                    JOptionPane.INFORMATION_MESSAGE);

            dispose();
        }
    }

    private void editar() {
        planoDeSaude.setOperadora(jTextFieldNomePlano.getText());
        planoDeSaude.setCategoria(jTextFieldCategoria.getText());
        planoDeSaude.setValidade(LocalDate.parse( jTextFieldValidade.getText(), DateTimeFormatter.ISO_DATE));

        PlanoDeSaudeDAO.atualizar(planoDeSaude);
        JOptionPane.showMessageDialog(
                this,
                "Plano de saúde editado com sucesso!",
                "Plano de saúde",
                JOptionPane.INFORMATION_MESSAGE);

        dispose();

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconeLabel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelValidade;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomePlano;
    private javax.swing.JTextField jTextFieldValidade;
    private javax.swing.JLabel labelCategoria;
    private java.awt.Panel panelBaixo;
    // End of variables declaration//GEN-END:variables
}
